// Code generated by protoc-gen-go.
// source: grpc.proto
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	AddRequest
	AddReturns
	SetCheckedRequest
	SetCheckedResponse
	RemoveRequest
	RemoveResponse
	ItemsRequest
	ItemStreamReturns
	Item
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddRequest struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type AddReturns struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *AddReturns) Reset()                    { *m = AddReturns{} }
func (m *AddReturns) String() string            { return proto.CompactTextString(m) }
func (*AddReturns) ProtoMessage()               {}
func (*AddReturns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddReturns) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type SetCheckedRequest struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Checked bool   `protobuf:"varint,2,opt,name=checked" json:"checked,omitempty"`
}

func (m *SetCheckedRequest) Reset()                    { *m = SetCheckedRequest{} }
func (m *SetCheckedRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCheckedRequest) ProtoMessage()               {}
func (*SetCheckedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetCheckedRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetCheckedRequest) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

type SetCheckedResponse struct {
}

func (m *SetCheckedResponse) Reset()                    { *m = SetCheckedResponse{} }
func (m *SetCheckedResponse) String() string            { return proto.CompactTextString(m) }
func (*SetCheckedResponse) ProtoMessage()               {}
func (*SetCheckedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RemoveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveResponse struct {
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ItemsRequest struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *ItemsRequest) Reset()                    { *m = ItemsRequest{} }
func (m *ItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*ItemsRequest) ProtoMessage()               {}
func (*ItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ItemsRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ItemsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ItemStreamReturns struct {
	Item  *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Index int64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Total int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
}

func (m *ItemStreamReturns) Reset()                    { *m = ItemStreamReturns{} }
func (m *ItemStreamReturns) String() string            { return proto.CompactTextString(m) }
func (*ItemStreamReturns) ProtoMessage()               {}
func (*ItemStreamReturns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ItemStreamReturns) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ItemStreamReturns) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ItemStreamReturns) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Item struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Created []byte `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Changed []byte `protobuf:"bytes,4,opt,name=changed,proto3" json:"changed,omitempty"`
	Checked bool   `protobuf:"varint,5,opt,name=checked" json:"checked,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetCreated() []byte {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Item) GetChanged() []byte {
	if m != nil {
		return m.Changed
	}
	return nil
}

func (m *Item) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "grpc.AddRequest")
	proto.RegisterType((*AddReturns)(nil), "grpc.AddReturns")
	proto.RegisterType((*SetCheckedRequest)(nil), "grpc.SetCheckedRequest")
	proto.RegisterType((*SetCheckedResponse)(nil), "grpc.SetCheckedResponse")
	proto.RegisterType((*RemoveRequest)(nil), "grpc.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "grpc.RemoveResponse")
	proto.RegisterType((*ItemsRequest)(nil), "grpc.ItemsRequest")
	proto.RegisterType((*ItemStreamReturns)(nil), "grpc.ItemStreamReturns")
	proto.RegisterType((*Item)(nil), "grpc.Item")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Grpc service

type GrpcClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc1.CallOption) (*AddReturns, error)
	SetChecked(ctx context.Context, in *SetCheckedRequest, opts ...grpc1.CallOption) (*SetCheckedResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc1.CallOption) (*RemoveResponse, error)
	Items(ctx context.Context, in *ItemsRequest, opts ...grpc1.CallOption) (Grpc_ItemsClient, error)
}

type grpcClient struct {
	cc *grpc1.ClientConn
}

func NewGrpcClient(cc *grpc1.ClientConn) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Add(ctx context.Context, in *AddRequest, opts ...grpc1.CallOption) (*AddReturns, error) {
	out := new(AddReturns)
	err := grpc1.Invoke(ctx, "/grpc.Grpc/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) SetChecked(ctx context.Context, in *SetCheckedRequest, opts ...grpc1.CallOption) (*SetCheckedResponse, error) {
	out := new(SetCheckedResponse)
	err := grpc1.Invoke(ctx, "/grpc.Grpc/SetChecked", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc1.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := grpc1.Invoke(ctx, "/grpc.Grpc/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) Items(ctx context.Context, in *ItemsRequest, opts ...grpc1.CallOption) (Grpc_ItemsClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_Grpc_serviceDesc.Streams[0], c.cc, "/grpc.Grpc/Items", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Grpc_ItemsClient interface {
	Recv() (*ItemStreamReturns, error)
	grpc1.ClientStream
}

type grpcItemsClient struct {
	grpc1.ClientStream
}

func (x *grpcItemsClient) Recv() (*ItemStreamReturns, error) {
	m := new(ItemStreamReturns)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Grpc service

type GrpcServer interface {
	Add(context.Context, *AddRequest) (*AddReturns, error)
	SetChecked(context.Context, *SetCheckedRequest) (*SetCheckedResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Items(*ItemsRequest, Grpc_ItemsServer) error
}

func RegisterGrpcServer(s *grpc1.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Add(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_SetChecked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCheckedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).SetChecked(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/SetChecked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).SetChecked(ctx, req.(*SetCheckedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Remove(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_Items_Handler(srv interface{}, stream grpc1.ServerStream) error {
	m := new(ItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcServer).Items(m, &grpcItemsServer{stream})
}

type Grpc_ItemsServer interface {
	Send(*ItemStreamReturns) error
	grpc1.ServerStream
}

type grpcItemsServer struct {
	grpc1.ServerStream
}

func (x *grpcItemsServer) Send(m *ItemStreamReturns) error {
	return x.ServerStream.SendMsg(m)
}

var _Grpc_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Grpc_Add_Handler,
		},
		{
			MethodName: "SetChecked",
			Handler:    _Grpc_SetChecked_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Grpc_Remove_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "Items",
			Handler:       _Grpc_Items_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x6c, 0x3e, 0x5a, 0xf5, 0x59, 0x4b, 0xbb, 0x16, 0x1a, 0x72, 0xd0, 0xb2, 0xa7, 0x82, 0x52,
	0xa4, 0x22, 0x88, 0xe0, 0xa1, 0x78, 0x10, 0xaf, 0xdb, 0x1f, 0x20, 0x31, 0xfb, 0xa8, 0xc1, 0xe6,
	0xc3, 0xcd, 0xab, 0x88, 0x7f, 0xd8, 0xbf, 0x21, 0xd9, 0x4d, 0x9a, 0xc4, 0x22, 0x78, 0xcb, 0x4c,
	0x66, 0xde, 0xee, 0x9b, 0x59, 0x80, 0xb5, 0xca, 0xc2, 0x79, 0xa6, 0x52, 0x4a, 0x99, 0x5b, 0x7c,
	0x73, 0x0e, 0xb0, 0x94, 0x52, 0xe0, 0xfb, 0x16, 0x73, 0x62, 0x63, 0xe8, 0x52, 0x44, 0x1b, 0xf4,
	0xac, 0xa9, 0x35, 0x3b, 0x12, 0x06, 0xf0, 0xcb, 0x52, 0x43, 0x5b, 0x95, 0xe4, 0xec, 0x0c, 0xdc,
	0x88, 0x30, 0xd6, 0x92, 0xe3, 0x05, 0xcc, 0xf5, 0xc8, 0x27, 0xc2, 0x58, 0x68, 0x9e, 0xdf, 0xc3,
	0x68, 0x85, 0xf4, 0xf0, 0x8a, 0xe1, 0x1b, 0xee, 0x06, 0x0f, 0xc0, 0x8e, 0x64, 0x39, 0xd5, 0x8e,
	0x24, 0xf3, 0xe0, 0x20, 0x34, 0x0a, 0xcf, 0x9e, 0x5a, 0xb3, 0x43, 0x51, 0x41, 0x3e, 0x06, 0xd6,
	0xb4, 0xe7, 0x59, 0x9a, 0xe4, 0xc8, 0xcf, 0xe1, 0x44, 0x60, 0x9c, 0x7e, 0xe0, 0x1f, 0x03, 0xf9,
	0x10, 0x06, 0x95, 0xa0, 0xb4, 0xdc, 0x41, 0xbf, 0xb8, 0x55, 0xde, 0xd8, 0x2d, 0x4a, 0x24, 0x7e,
	0x6a, 0x93, 0x23, 0x0c, 0x28, 0xd8, 0x30, 0xdd, 0x26, 0xa4, 0xaf, 0xe1, 0x08, 0x03, 0xf8, 0x33,
	0x8c, 0x0a, 0xef, 0x8a, 0x14, 0x06, 0xf1, 0x3f, 0x17, 0xaf, 0x0f, 0xb0, 0x7f, 0x1d, 0x40, 0x29,
	0x05, 0x1b, 0xcf, 0x31, 0xac, 0x06, 0xfc, 0x0b, 0xdc, 0xc2, 0xb9, 0x97, 0xcb, 0xae, 0x00, 0xbb,
	0x51, 0x80, 0x4e, 0x4b, 0x61, 0x40, 0x28, 0xf5, 0x94, 0xbe, 0xa8, 0xa0, 0xc9, 0x31, 0x48, 0xd6,
	0x28, 0x3d, 0xb7, 0xfc, 0x63, 0x60, 0x33, 0xe1, 0x6e, 0x2b, 0xe1, 0xc5, 0xb7, 0x05, 0xee, 0xa3,
	0xca, 0x42, 0x76, 0x01, 0xce, 0x52, 0x4a, 0x36, 0x34, 0x9b, 0xd4, 0xcf, 0xc0, 0x6f, 0x32, 0x7a,
	0x77, 0xde, 0x61, 0x4b, 0x80, 0xba, 0x17, 0x36, 0x31, 0x8a, 0xbd, 0xa2, 0x7d, 0x6f, 0xff, 0x47,
	0xd9, 0x47, 0x87, 0xdd, 0x40, 0xcf, 0x74, 0xc4, 0x4e, 0x8d, 0xaa, 0x55, 0xa9, 0x3f, 0x6e, 0x93,
	0x3b, 0xdb, 0x2d, 0x74, 0x75, 0x91, 0x8c, 0xd5, 0x91, 0x57, 0xad, 0xfa, 0x93, 0x9a, 0x6b, 0xb5,
	0xc5, 0x3b, 0x57, 0xd6, 0x4b, 0x4f, 0xbf, 0xf4, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd,
	0x43, 0x57, 0x84, 0xf7, 0x02, 0x00, 0x00,
}
